### 最大池化层、平均池化层

In [45]:
import torch
from torch import nn
from d2l import torch as d2l

In [46]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros([X.shape[0]-p_h+1, X.shape[1]-p_w+1])
    
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i+p_h, j:j+p_w].max()
            elif mode== 'mean':
                Y[i, j] = X[i:i+p_h, j:j+p_w].mean()
    
    return Y
    
X = torch.tensor([
    [0., 1., 2.],
    [3., 4., 5.],
    [6., 7., 8.],
])
pool2d(X, [2, 2], 'max')

tensor([[4., 5.],
        [7., 8.]])

In [47]:
pool2d(X, [2, 2], 'mean')

tensor([[2., 3.],
        [5., 6.]])

### 填充与步幅

In [48]:
X = torch.arange(16, dtype=torch.float32).reshape([1, 1, 4, 4])
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

无填充与步幅

In [49]:
pool2d_3 = nn.MaxPool2d(3)
pool2d_3(X)

tensor([[[[10.]]]])

设定填充与步幅

In [50]:
pool2d_3 = nn.MaxPool2d(3, padding=1, stride=2)
pool2d_3(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

设定矩形核

In [51]:
pool2d_23 = nn.MaxPool2d((2, 3), padding=(0, 1), stride=(2, 3))
pool2d_23(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

### 多通道

In [52]:
# pooling layer 是在每个通道上单独运算，而不是像卷积一样对所有通道汇总
X = torch.cat((X, X+1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [53]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])