>* ***奇异值分解（Singular Value Decomposition，SVD）***：将矩阵分解为奇异向量和奇异值。所有实矩阵都可进行奇异值分解  
>$$A=U\Sigma V^\top$$  
>>$A:m×n$  
>>$U:m×m$：其列向量为左奇异向量  
>>$ \Sigma :m×n$：对角矩阵，其对角元素为$A$的奇异值  
>>$V:n×n$：其列向量为右奇异向量  

In [1]:
import numpy as np

A = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])

U, D, V = np.linalg.svd(A)

print("U:" + '\n', U)
print("D:" + '\n', D)
print("V:" + '\n', V)


U:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
D:
 [9.508032   0.77286964]
V:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
