* ***标量（scalar）***：单独一个数  
* ***向量（vector）***：表示一列有序排列数  
* ***矩阵（matrix）***：二维数组
* ***张量（tensor）***：超过二维的数组

In [2]:
import numpy as np

# 标量
s = 5
# 向量
v = np.array([1,2])
# 矩阵
m = np.array([[1,2], [3,4]])
# 张量
t = np.array([
[[1,2,3],[4,5,6],[7,8,9]],
[[11,12,13],[14,15,16],[17,18,19]],
[[21,22,23],[24,25,26],[27,28,29]],
])
print("标量: " + '\n' + str(s))
print("向量: " + '\n' + str(v))
print("矩阵: " + '\n' + str(m))
print("张量: " + '\n' + str(t))


标量: 
5
向量: 
[1 2]
矩阵: 
[[1 2]
 [3 4]]
张量: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
