* ***矩阵乘法***：记为$AB$
* ***Hadamard乘积***：记为$A \odot B$，对应元素相乘
* ***点乘（Dot Product）/内积***：相同维数的向量间对应元素相乘再相加

In [1]:
import numpy as np

m1 = np.array([[1.0,3.0],[1.0,0.0]])
m2 = np.array([[1.0,2.0],[5.0,0.0]])
print("按矩阵乘法规则：" + '\n', np.dot(m1, m2))
print("按逐元素相乘：" + '\n', np.multiply(m1, m2))
print("按逐元素相乘：" + '\n', m1*m2)
v1 = np.array([1.0,2.0])
v2 = np.array([4.0,5.0])
print("向量内积：" + '\n', np.dot(v1, v2))

按矩阵乘法规则：
 [[16.  2.]
 [ 1.  2.]]
按逐元素相乘：
 [[1. 6.]
 [5. 0.]]
按逐元素相乘：
 [[1. 6.]
 [5. 0.]]
向量内积：
 14.0
