In [29]:
import torch

In [30]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [31]:
x.requires_grad_(True) #表示需要存储梯度，等价于x=torch.arange(4.0,requires_grad=True)
x.grad #默认为None

In [32]:
y=2*torch.dot(x,x) #定义y函数
y

tensor(28., grad_fn=<MulBackward0>)

In [33]:
y.backward() #求导
x.grad, (x.grad==4*x) #访问导数

(tensor([ 0.,  4.,  8., 12.]), tensor([True, True, True, True]))

In [37]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [40]:
# 当y不是标量而是向量时
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [41]:
# 分离计算
x.grad.zero_()
y=x*x
u=y.detach() #将y视为一个常数并等于u
z=u*x

z.sum().backward()
x.grad,x.grad==u

(tensor([0., 1., 4., 9.]), tensor([True, True, True, True]))

In [27]:
# python控制流的梯度计算
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()
a.grad, a.grad==d/a

(tensor(1024.), tensor(True))