In [1]:
import torch
import torch.nn.functional as F
from torch import nn

# 自定义层：不带参数的层
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [2]:
net = nn.Sequential(
    nn.Linear(8, 128),
    CenteredLayer()
)

Y = net(torch.rand(4, 8))
Y.mean()

tensor(0., grad_fn=<MeanBackward0>)

In [14]:
# 自定义层：带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.8565,  0.1178, -1.8355],
        [-0.2044,  1.3092, -0.8906],
        [-1.4571,  0.2982,  1.0843],
        [ 0.7842, -1.3470, -1.2367],
        [-0.2070, -0.1640, -1.0267]], requires_grad=True)

In [17]:
# 使用自定义层进行前向计算
linear(torch.rand(2,5))     

tensor([[0.5561, 0.0000, 0.0000],
        [0.2799, 0.4494, 0.0000]])

In [22]:
# 使用自定义层构造模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.1558],
        [0.0000]])