**矩阵转置（transpose）**：沿着对角线反转

In [2]:
import numpy as np

A = np.array([[1.0,2.0],[1.0,0.0],[2.0,3.0]])
A_t = np.transpose(A)
print("A:" + '\n' + str(A))
print("A的转置:" + '\n' + str(A_t))


A:
[[1. 2.]
 [1. 0.]
 [2. 3.]]
A的转置:
[[1. 1. 2.]
 [2. 0. 3.]]
